### ISSUE TITLE
JSON error on input

### ISSUE THREAD

**Issue by boettges** [notDavid/alfred-workflow-synonyms#2]
Hello David,

I wanted to try out your synonyms workflow and upon initiation I get:
`Starting debug for 'Synonyms'

[2018-02-25 23:07:28][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
None`
… on both the synonyms and antonyms search.

According to packal I'm on v1.1

I already applied to get API access from synonyms.net, as I thought that the workflow's standard account might be over quota, btut that did not solve the issue.

Thanks a lo tin advance

**Comment by notDavid** [comment]
Hi there @boettges,

I quickly hacked something together, please remove the Synonyms workflow from your Alfred.
Then download and try this version...:  https://github.com/notDavid/alfred-workflow-synonyms/raw/master/Synonyms.alfredworkflow

**Comment by boettges** [comment]
works perfectly 👌

Thanks a lot

**Comment by notDavid** [comment]
Good, you're welcome! :-)
